# Generated by Django 5.2.17 on 2026-08-27 09:32

import utils.data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_branch'),
        ('dashboard', '0002_initial'),
        ('service', '0002_alter_service_options_service_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['order', '-updated_at'], 'verbose_name': 'پزشک', 'verbose_name_plural': 'پزشکان'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='about.branch', verbose_name='مطب\u200cهای محل کار'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certifications',
            field=models.TextField(blank=True, default='', help_text='هر مورد در یک خط', verbose_name='دوره\u200cها و گواهی\u200cنامه\u200cها'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(blank=True, default='', help_text='مثلاً: دکترای حرفه\u200cای دندانپزشکی', max_length=120, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True, default='', help_text='هر مورد در یک خط، مثلاً: دکترای دندانپزشکی — دانشگاه علوم پزشکی مشهد، ۱۳۹۲', verbose_name='تحصیلات'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.TextField(blank=True, default='', help_text='هر مورد در یک خط', verbose_name='سوابق کاری'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال\u200cهای تجربه'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='headline',
            field=models.CharField(blank=True, default='', help_text='یک خط زیر نام، مثلاً: دندانپزشک، متخصص ایمپلنت و زیبایی', max_length=180, verbose_name='عنوان کوتاه'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_published',
            field=models.BooleanField(default=True, help_text='اگر خاموش باشد صفحه\u200cی رزومه ۴۰۴ می\u200cدهد و از sitemap حذف می\u200cشود', verbose_name='نمایش صفحه عمومی'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='شماره نظام پزشکی'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='memberships',
            field=models.TextField(blank=True, default='', help_text='هر مورد در یک خط، مثلاً: عضو انجمن دندانپزشکی ایران', verbose_name='عضویت\u200cها'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='خالی بگذارید تا از عنوان کوتاه و تخصص ساخته شود', max_length=300, verbose_name='توضیح متا'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='service.service', verbose_name='خدمات تخصصی'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slug',
            # Added without `unique` on purpose — every existing row would get
            # the same empty default and the index would collide. The
            # constraint arrives in the next migration, after the backfill.
            field=models.SlugField(allow_unicode=True, blank=True, default='', help_text='خالی بگذارید تا از نام و نام خانوادگی ساخته شود', max_length=200, verbose_name='نشانی صفحه'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, default='', help_text='مثلاً: ایمپلنت و جراحی دهان و دندان', max_length=120, verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(default='توضیحات پزشک هنوز ثبت نشده است', validators=[utils.data.validators.validate_length], verbose_name='معرفی'),
        ),
    ]
