# Generated by Django 4.2 on 2025-03-09 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gallery.models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_created_at_category_updated_at_and_more'),
        ('dashboard', '__first__'),
        ('gallery', '0002_image_remove_gallery_title_alter_gallery_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-updated_at'], 'verbose_name': 'گالری', 'verbose_name_plural': 'گالری\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_galleries', to='dashboard.doctor'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_galleries', to='core.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=gallery.models.gallery_image_upload_path, validators=[utils.validators.validate_image]),
        ),
    ]
