# Generated by Django 4.2 on 2025-02-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_doctor_remove_doctor2_user'),
        ('gallery', '0002_image_remove_gallery_title_alter_gallery_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_galleries', to='dashboard.doctor'),
            preserve_default=False,
        ),
    ]
