# Generated by Django 4.2 on 2025-02-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('dashboard', '0005_alter_doctor_description'),
        ('gallery', '0003_gallery_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries', to='core.category'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_galleries', to='dashboard.doctor'),
        ),
    ]
