# Generated by Django 5.1.7 on 2025-04-06 08:12

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='users', validators=[utils.validators.validate_image]),
        ),
    ]
