# Generated by Django 5.1.7 on 2026-07-30 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contact_message', 'پیام تماس جدید'), ('appointment', 'نوبت جدید'), ('bulk', 'ارسال گروهی')], max_length=32, verbose_name='نوع')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('partial', 'ارسال ناقص')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='تعداد گیرنده')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='ارسال\u200cشده')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='ناموفق')),
                ('recipients', models.TextField(blank=True, default='', verbose_name='گیرندگان')),
                ('error', models.TextField(blank=True, default='', verbose_name='خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'گزارش اعلان',
                'verbose_name_plural': 'گزارش اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'kind'], name='notificatio_created_455301_idx')],
            },
        ),
    ]
