# Generated by Django 5.1.7 on 2026-07-31 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام گروه')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='توضیح')),
                ('numbers', models.TextField(help_text='با فاصله، کاما یا خط جدید جدا کنید', verbose_name='شماره\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_groups', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'گروه مخاطبان',
                'verbose_name_plural': 'گروه\u200cهای مخاطبان',
                'ordering': ['name'],
            },
        ),
    ]
