# Generated by Django 5.1.7 on 2026-08-23 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_contactgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='آدرس مقصد')),
                ('p256dh', models.CharField(max_length=255, verbose_name='کلید عمومی مرورگر')),
                ('auth', models.CharField(max_length=255, verbose_name='کلید احراز')),
                ('user_agent', models.CharField(blank=True, default='', max_length=300, verbose_name='مرورگر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک اعلان',
                'verbose_name_plural': 'اشتراک\u200cهای اعلان',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_2bc4e1_idx')],
            },
        ),
    ]
