# Generated by Django 4.2 on 2025-03-09 14:39

from django.db import migrations, models
import django.utils.timezone
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_options_service_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(validators=[utils.validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service_images/', validators=[utils.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, validators=[utils.validators.validate_slug]),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, unique=True, validators=[utils.validators.validate_title]),
        ),
    ]
