# Generated by Django 5.1.7 on 2025-04-06 08:00

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='banner_images/%Y/%m/%d', validators=[utils.validators.validate_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[utils.validators.validate_phone])),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(validators=[utils.validators.validate_length])),
                ('image', models.ImageField(upload_to='clinic_images', validators=[utils.validators.validate_image])),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مطب',
                'verbose_name_plural': 'مطب\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دو\u200cشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], help_text='روز هفته')),
                ('morning_start', models.IntegerField(blank=True, help_text='ساعت شروع شیفت صبح (0-23)', null=True)),
                ('morning_end', models.IntegerField(blank=True, help_text='ساعت پایان شیفت صبح (0-23)', null=True)),
                ('evening_start', models.IntegerField(blank=True, help_text='ساعت شروع شیفت عصر (0-23)', null=True)),
                ('evening_end', models.IntegerField(blank=True, help_text='ساعت پایان شیفت عصر (0-23)', null=True)),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('day',), name='unique_day')],
            },
        ),
    ]
