# Generated by Django 4.2 on 2025-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_alter_clinic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
