# Generated by Django 5.1.7 on 2025-03-27 08:37

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner_images/%Y/%m/%d', validators=[utils.validators.validate_image]),
        ),
    ]
