# Generated by Django 5.1.7 on 2025-03-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_banner_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['created_at'], 'verbose_name': 'بنر', 'verbose_name_plural': 'بنرها'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='updated_at',
        ),
    ]
