# Generated by Django 5.1.7 on 2025-03-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_banner_options_remove_banner_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
