# Generated by Django 5.1.7 on 2025-10-04 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان خدمت')),
                ('price', models.DecimalField(decimal_places=9, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تعرفه خدمت',
                'verbose_name_plural': 'تعرفه\u200cهای خدمات',
                'ordering': ['title'],
            },
        ),
    ]
