# Generated by Django 5.1.7 on 2026-07-23 14:32

import utils.data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_clinic_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(max_length=11, validators=[utils.data.validators.validate_phone]),
        ),
    ]
