# Generated by Django 5.1.7 on 2026-07-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clinic_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='ساعات کاری را به صورت متن ساده وارد کنید. هر خط جدید یک بخش جداگانه نمایش داده می\u200cشود.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ساعات کاری',
                'verbose_name_plural': 'ساعات کاری',
            },
        ),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
    ]
