# Generated by Django 5.1.7 on 2026-07-28 13:59 (data-copy step added by hand).

from django.db import migrations


def copy_clinic_to_about(apps, schema_editor):
    """Copy the sole Clinic row (if any) into about.About before we drop it."""
    Clinic = apps.get_model('core', 'Clinic')
    About = apps.get_model('about', 'About')
    for src in Clinic.objects.all():
        # Singleton on both sides — a naive .create() is fine (nothing to collide with).
        About.objects.create(
            name=src.name,
            address=src.address,
            phone=src.phone,
            email=src.email,
            description=src.description,
            image=src.image,
            created_at=src.created_at,
            updated_at=src.updated_at,
        )


def copy_hours_to_about(apps, schema_editor):
    ClinicHours = apps.get_model('core', 'ClinicHours')
    WorkingHours = apps.get_model('about', 'WorkingHours')
    for src in ClinicHours.objects.all():
        WorkingHours.objects.create(text=src.text, updated_at=src.updated_at)


def noop(apps, schema_editor):
    """Reverse is a no-op — the old tables no longer exist after forward migration."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_clinic_options_remove_clinic_is_primary_and_more'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_clinic_to_about, noop),
        migrations.RunPython(copy_hours_to_about, noop),
        migrations.DeleteModel(name='Clinic'),
        migrations.DeleteModel(name='ClinicHours'),
    ]
