# Generated by Django 4.2 on 2025-03-05 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='users/default.png', upload_to='users'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="نام کاربری فقط می\u200cتواند شامل حروف، اعداد، '_', '@', '.', '+', و '-' باشد. همچنین نمی\u200cتواند فقط عدد یا فقط کاراکترهای خاص باشد", regex='^(?!\\d+$)(?![_\\W]+$)[a-zA-Z0-9_@.+-]+$')]),
        ),
    ]
