# Generated by Django 4.2 on 2025-03-09 14:39

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_date_joined_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='users/default.png', upload_to='users', validators=[utils.validators.validate_image]),
        ),
    ]
