# Generated by Django 5.1.7 on 2025-03-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_image_customuser_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_image',
            new_name='image',
        ),
    ]
