# Generated by Django 5.1.7 on 2026-07-28 13:59

import utils.data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=11, validators=[utils.data.validators.validate_phone])),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(validators=[utils.data.validators.validate_length])),
                ('image', models.ImageField(upload_to='about', validators=[utils.data.validators.validate_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='ساعات کاری را به صورت متن ساده وارد کنید. هر خط جدید یک بخش جداگانه نمایش داده می\u200cشود.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ساعات کاری',
                'verbose_name_plural': 'ساعات کاری',
            },
        ),
    ]
