# Generated by Django 5.1.7 on 2026-07-31 10:13

import utils.data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='extra_phones',
            field=models.TextField(blank=True, default='', help_text='هر شماره در یک خط، یا با کاما جدا کنید', verbose_name='شماره\u200cهای دیگر'),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(help_text='شماره\u200cای که روی دکمه\u200cی تماس در همه\u200cی صفحات نمایش داده می\u200cشود', max_length=11, validators=[utils.data.validators.validate_phone], verbose_name='تلفن اصلی'),
        ),
    ]
