# Generated by Django 5.2.17 on 2026-08-27 09:32

import utils.data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_extra_phones_alter_about_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='مثلاً: مشهد', max_length=60, unique=True, verbose_name='شهر')),
                ('title', models.CharField(blank=True, default='', help_text='خالی بگذارید تا «مطب دندانپزشکی <شهر>» ساخته شود', max_length=120, verbose_name='عنوان نمایشی')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, verbose_name='کد پستی')),
                ('phone', models.CharField(max_length=11, validators=[utils.data.validators.validate_phone], verbose_name='تلفن')),
                ('extra_phones', models.TextField(blank=True, default='', help_text='هر شماره در یک خط، یا با کاما جدا کنید', verbose_name='شماره\u200cهای دیگر')),
                ('hours', models.TextField(blank=True, default='', help_text='خالی بگذارید تا ساعات کاری عمومی سایت نمایش داده شود', verbose_name='ساعات کاری این مطب')),
                ('map_embed_url', models.URLField(blank=True, default='', help_text='آدرس src داخل تگ iframe نقشه گوگل یا نشان', max_length=1000, verbose_name='لینک embed نقشه')),
                ('map_link', models.URLField(blank=True, default='', help_text='لینکی که کاربر با زدنش در نقشه مسیر می\u200cگیرد', max_length=1000, verbose_name='لینک مسیریابی')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('is_primary', models.BooleanField(default=False, help_text='آدرسی که در داده ساختاریافته\u200cی کل سایت استفاده می\u200cشود', verbose_name='مطب اصلی')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مطب',
                'verbose_name_plural': 'مطب\u200cها',
                'ordering': ['-is_primary', 'order', 'city'],
            },
        ),
    ]
