# Generated by Django 5.2.17 on 2026-08-28 12:13

from django.db import migrations, models


def carry_hours_onto_the_practices(apps, schema_editor):
    """
    Move the one site-wide opening-hours row onto every practice that has none.

    Deleting `WorkingHours` without this would blank the hours in the footer
    of every page — the text is staff-written and there is no other copy of
    it. A practice that already has its own hours keeps them.
    """
    WorkingHours = apps.get_model('about', 'WorkingHours')
    Branch = apps.get_model('about', 'Branch')

    row = WorkingHours.objects.first()
    if row and row.text:
        Branch.objects.filter(hours='').update(hours=row.text)


def noop(apps, schema_editor):
    """Reverse leaves the copied text on each branch; nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_branch'),
        # `core.0007` populates `about.WorkingHours` from the old `core` table
        # in a RunPython. Without this edge the graph is free to run the
        # delete below first, and that data step would then fail on a model
        # its historical registry no longer has.
        ('core', '0007_delete_clinic_delete_clinichours'),
    ]

    operations = [
        migrations.RunPython(carry_hours_onto_the_practices, noop),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['order', 'city'], 'verbose_name': 'مطب', 'verbose_name_plural': 'مطب\u200cها'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='address',
        ),
        migrations.RemoveField(
            model_name='about',
            name='extra_phones',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='branch',
            name='hours',
            field=models.TextField(blank=True, default='', help_text='هر خط یک بازه — مثلاً «شنبه تا چهارشنبه: ۹ الی ۱۳ و ۱۶ الی ۲۰»', verbose_name='ساعات کاری این مطب'),
        ),
    ]
