# Generated by Django 5.1.7 on 2026-07-30 19:10

import django.db.models.deletion
import utils.data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('time', models.TimeField(verbose_name='ساعت')),
                ('is_active', models.BooleanField(default=True, help_text='غیرفعال کردن، نوبت\u200cهای ثبت\u200cشده را حذف نمی\u200cکند', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='dashboard.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'زمان نوبت\u200cدهی',
                'verbose_name_plural': 'زمان\u200cهای نوبت\u200cدهی',
                'ordering': ['weekday', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='شنبه\u200cی هفته\u200cای که این نوبت به آن تعلق دارد', verbose_name='شروع هفته')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, validators=[utils.data.validators.validate_national_code], verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=11, validators=[utils.data.validators.validate_phone], verbose_name='شماره تماس')),
                ('note', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('booked', 'رزرو شده'), ('cancelled', 'لغو شده')], default='booked', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.availabilityslot', verbose_name='زمان نوبت')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-week_start', 'slot__weekday', 'slot__time'],
            },
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('doctor', 'weekday', 'time'), name='unique_doctor_weekday_time'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['week_start', 'status'], name='appointment_week_st_e5f2f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('slot', 'week_start'), name='unique_active_booking_per_slot_week'),
        ),
    ]
