# Generated by Django 5.2.17 on 2026-08-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_branch'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='مطبی که این نوبت در آن انجام می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_slots', to='about.branch', verbose_name='مطب'),
        ),
    ]
