# Generated by Django 5.1.7 on 2026-07-23 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_pricingitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingitem',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)'),
        ),
    ]
