# Generated by Django 5.1.7 on 2026-07-24 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_pricingitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام دسته')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='عدد کوچک\u200cتر بالاتر نمایش داده می\u200cشود', verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی تعرفه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای تعرفه',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='pricing.pricingcategory', verbose_name='دسته\u200cبندی'),
        ),
    ]
