# Generated by Django 5.1.7 on 2025-03-14 20:34

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[utils.validators.validate_phone])),
                ('message', models.TextField(validators=[utils.validators.validate_length])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دو\u200cشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], help_text='روز هفته')),
                ('morning_start', models.IntegerField(blank=True, help_text='ساعت شروع شیفت صبح (0-23)', null=True)),
                ('morning_end', models.IntegerField(blank=True, help_text='ساعت پایان شیفت صبح (0-23)', null=True)),
                ('evening_start', models.IntegerField(blank=True, help_text='ساعت شروع شیفت عصر (0-23)', null=True)),
                ('evening_end', models.IntegerField(blank=True, help_text='ساعت پایان شیفت عصر (0-23)', null=True)),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('day',), name='unique_day')],
            },
        ),
    ]
