# Generated by Django 5.1.7 on 2025-03-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkingHours',
        ),
    ]
