# Generated by Django 5.1.7 on 2025-04-06 08:00

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='توضیحات پزشک هنوز ثبت نشده است', validators=[utils.validators.validate_length])),
                ('twitter', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('telegram', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
                'ordering': ['-updated_at'],
            },
        ),
    ]
