# Generated by Django 5.1.7 on 2025-03-14 20:26

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='توضیحات پزشک هنوز ثبت نشده است', validators=[utils.validators.validate_length])),
                ('twitter', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('telegram', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user associated with this doctor.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
                'ordering': ['-updated_at'],
            },
        ),
    ]
