# Generated by Django 5.1.7 on 2025-04-06 08:00

import django_ckeditor_5.fields
import functools
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(validators=[functools.partial(utils.validators.validate_length, *(), **{'max_length': 20000, 'min_length': 50})])),
                ('image', models.ImageField(upload_to='blog_images', validators=[utils.validators.validate_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='blog_posts', to='core.category')),
            ],
            options={
                'verbose_name': 'وبلاگ',
                'verbose_name_plural': 'وبلاگ ها',
                'ordering': ['-updated_at'],
            },
        ),
    ]
