# Generated by Django 5.1.7 on 2025-03-15 20:35

import django_ckeditor_5.fields
import functools
import utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(validators=[functools.partial(utils.validators.validate_length, *(), **{'max_length': 20000, 'min_length': 50})]),
        ),
    ]
