# Generated by Django 5.1.7 on 2026-07-23 14:32

import utils.data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=11, validators=[utils.data.validators.validate_phone]),
        ),
    ]
