# Generated by Django 5.2.17 on 2026-08-27 09:32

import django.db.models.deletion
import django_ckeditor_5.fields
import utils.data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', help_text='توضیح کامل خدمت؛ همین متن است که در گوگل رتبه می\u200cگیرد', verbose_name='متن کامل'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='خالی بگذارید تا از توضیح کوتاه ساخته شود', max_length=300, verbose_name='توضیح متا'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='خالی بگذارید تا از عنوان خدمت ساخته شود', max_length=200, verbose_name='عنوان متا'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            # Added without `unique` on purpose — see the dashboard migration.
            field=models.SlugField(allow_unicode=True, blank=True, default='', help_text='خالی بگذارید تا از عنوان ساخته شود', max_length=200, verbose_name='نشانی صفحه'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='متنی که در کارت خدمت و در نتایج جست\u200cوجو دیده می\u200cشود', validators=[utils.data.validators.validate_length], verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service_images/', validators=[utils.data.validators.validate_image], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سؤال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='service.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'سؤال متداول خدمت',
                'verbose_name_plural': 'سؤالات متداول خدمات',
                'ordering': ['order', 'id'],
            },
        ),
    ]
