# Generated by Django 5.2.17 on 2026-08-28 12:31

import django_ckeditor_5.fields
import utils.data.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='متنی که در کارت خدمت و بالای صفحه\u200cی خدمت دیده می\u200cشود؛ می\u200cتوانید بخشی از آن را پررنگ یا فهرست کنید', validators=[utils.data.validators.validate_rich_length], verbose_name='توضیح کوتاه'),
        ),
    ]
