# Generated by Django 4.2 on 2025-02-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دو\u200cشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], help_text='روز هفته')),
                ('morning_start', models.IntegerField(blank=True, null=True, verbose_name='شروع صبح')),
                ('morning_end', models.IntegerField(blank=True, null=True, verbose_name='پایان صبح')),
                ('evening_start', models.IntegerField(blank=True, null=True, verbose_name='شروع عصر')),
                ('evening_end', models.IntegerField(blank=True, null=True, verbose_name='پایان عصر')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
            },
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(fields=('day',), name='unique_day'),
        ),
    ]
