# Generated by Django 4.2 on 2025-02-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['day'], 'verbose_name': 'ساعت کاری', 'verbose_name_plural': 'ساعات کاری'},
        ),
    ]
