# Generated by Django 5.1.4 on 2025-01-14 08:44

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
    ]
