# Generated by Django 4.2 on 2025-02-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_doctor_remove_doctor2_user'),
        ('blog', '0003_alter_blogpost_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_posts', to='dashboard.doctor'),
        ),
    ]
