# Generated by Django 4.2 on 2025-03-09 14:39

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clinic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='نام فقط می\u200cتواند شامل حروف، اعداد و علائم نگارشی رایج باشد', regex='^[a-zA-Z0-9\\u0600-\\u06FF\\s\\.,!?():;"\\\'\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='آدرس فقط می\u200cتواند شامل حروف، اعداد و علائم نگارشی رایج باشد', regex='^[a-zA-Z0-9\\u0600-\\u06FF\\s\\.,!?():;"\\\'\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='description',
            field=models.TextField(validators=[utils.validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(upload_to='clinic_images', validators=[utils.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='نام فقط می\u200cتواند شامل حروف، اعداد و علائم نگارشی رایج باشد', regex='^[a-zA-Z0-9\\u0600-\\u06FF\\s\\.,!?():;"\\\'\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(max_length=20, validators=[utils.validators.validate_phone]),
        ),
    ]
