# Generated by Django 5.1.7 on 2025-03-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دو\u200cشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], help_text='روز هفته')),
                ('morning_start', models.IntegerField(blank=True, help_text='ساعت شروع شیفت صبح (0-23)', null=True)),
                ('morning_end', models.IntegerField(blank=True, help_text='ساعت پایان شیفت صبح (0-23)', null=True)),
                ('evening_start', models.IntegerField(blank=True, help_text='ساعت شروع شیفت عصر (0-23)', null=True)),
                ('evening_end', models.IntegerField(blank=True, help_text='ساعت پایان شیفت عصر (0-23)', null=True)),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('day',), name='unique_day')],
            },
        ),
    ]
