# Generated by Django 5.1.7 on 2025-03-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_clinic_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
