# Generated by Django 5.1.7 on 2026-07-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
