# Generated by Django 4.2 on 2025-02-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_delete_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
