# Generated by Django 4.2 on 2025-02-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_doctor_created_at_doctor_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(default='توضیحات پزشک هنوز ثبت نشده است.'),
        ),
    ]
