# Generated by Django 4.2 on 2025-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otp_options_alter_otp_code_alter_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
